name: AHQ Store Issues Bot

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write

jobs:
  bot:
    name: AHQ Store Bot Auto Response

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v4

      - name: Install deps
        run: npm i .
        working-directory: events

      - name: Check Queue
        uses: ahmadnassri/action-workflow-queue@v1

      - name: Pull
        run: git pull

      - name: Run
        uses: actions/github-script@v7
        with:
          script: |
            require("./events/issue_comment/index.js")(github, context)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          author_name: AHQ Store Bot
          message: Refresh Entries
